#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

for (( i=0; i<10; i++))
do
echo "Best School" 
done
#^c

#for (( assign my initial value; what is my condition to do this; when i am doing add 1 to my value and check again))
#let's do it
#the stuff i am doing
#i finish doing the stuff for this round/loop
