#!/usr/bin/env bash
#help: read

#Write a Bash script that displays the content of the file /etc/passwd.

#Your script should only display:

#username
#user id
#Home directory path for the user
#Requirements:

#You must use the while loop

while IFS= read -r line; do
    username=$(echo "$line" | cut -d: -f1)
    userid=$(echo "$line" | cut -d: -f3)
    Homedirectory=$(echo "$line" | cut -d: -f6)
    echo "$username:$userid:$Homedirectory"
done < /etc/passwd