#!/usr/bin/env bash
#The file /etc/passwd has already been covered in a previous project and you should be familiar with it. Today we will make up a story based on it.

#Write a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

#Format: The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO

#Requirements:

#You must use the while loop

IFS=":"
while read -r username password userid groupid userdescription homedirectory shell; do
    echo "The user $username is part of the $groupid gang, lives in $homedirectory and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $userdescription"
done < /etc/passwd
