#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop
# diplays hi when we hit 9

count=1

while [ $count -le 10 ]
do
    echo "Best School"
    #if 9 say hi
    if [ $count == 9 ]
    then
	echo "hi"
    fi
  (( count++ ))
done

