#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop

count=1

while [ $count -le 10 ]
do
    #if 4 say bad luck
    if [ $count == 4 ]
    then
	echo "bad luck"
    elif [ $count == 8 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi
  (( count++ ))
done
