#!/usr/bin/env bash
#Write a Bash script that gives you information about the school file.

#Requirements:

#You must use if and, else 
#Your Bash script should check if the file exists and print:
#if the file exists: school file exists
#if the file does not exist: school file does not exist
#If the file exists, print:
#if the file is empty: school file is empty
#if the file is not empty: school file is not empty
#if the file is a regular file: school is a regular file
#if the file is not a regular file: (nothing)

if [[ -e "school" ]]; then
    echo "school file exists"
    if [[ -f "school" ]]; then
	if [[ -s "school" ]]; then
	    echo "school file is not empty"
        else
	    echo "school file is empty"
        fi 
        echo "school is a regular file"
    else
	echo "school file is empty"
    fi
else
    echo "school file does not exist"
fi
